name: Release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Release

    runs-on: ubuntu-20.04

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies and build
        run: npm install pnpm -g && pnpm install && pnpm build

      - name: Pack directory
        id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ./dist
          zipFilePath: extension.zip

      - name: Get oauth token
        run: |
          echo 'GOOGLE_RESPONSE<<EOF' >>$GITHUB_ENV
          curl https://accounts.google.com/o/oauth2/token -d "client_id=${{ secrets.GOOGLE_CLIENT_ID }}&client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }}&code=${{ secrets.GOOGLE_CODE }}&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob" >>$GITHUB_ENV
          echo 'EOF' >>$GITHUB_ENV

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "upload" # one of: upload, publish, testers
          client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh_token: ${{ fromJson(env.GOOGLE_RESPONSE).refresh_token }}
          extension_id: "lflpklblpjagndghmjjegalblijlccmh"
          zip_file: "./extension.zip"
